"""updated system metric

Revision ID: 617ede3e77f6
Revises: 9541d0ab07d0
Create Date: 2025-12-15 09:42:40.257168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '617ede3e77f6'
down_revision: Union[str, Sequence[str], None] = '9541d0ab07d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_metrics', 'memory_usage')
    op.drop_column('system_metrics', 'disk_usage')
    op.drop_column('system_metrics', 'cpu_usage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_metrics', sa.Column('cpu_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('system_metrics', sa.Column('disk_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('system_metrics', sa.Column('memory_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
