"""added start time to feed table

Revision ID: 274ff5a47469
Revises: b36b48ed7cd8
Create Date: 2025-12-18 10:21:50.217051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '274ff5a47469'
down_revision: Union[str, Sequence[str], None] = 'b36b48ed7cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera_feeds', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('camera_feeds', 'start_time')
    # ### end Alembic commands ###
