"""create camera feeds tables

Revision ID: f0175d68ad7b
Revises: a6d485f97a08
Create Date: 2025-11-26 15:00:01.653804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0175d68ad7b'
down_revision: Union[str, Sequence[str], None] = 'a6d485f97a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_feeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('feed_url', sa.String(length=1024), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('feed_type', sa.String(length=50), nullable=True),
    sa.Column('custom_instruction', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('current_detections', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_feeds_id'), 'camera_feeds', ['id'], unique=False)
    op.create_table('feed_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.Column('sound_enabled', sa.Boolean(), nullable=True),
    sa.Column('sensitivity', sa.String(length=20), nullable=True),
    sa.Column('auto_record', sa.Boolean(), nullable=True),
    sa.Column('record_duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['camera_feeds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_id')
    )
    op.create_index(op.f('ix_feed_settings_id'), 'feed_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feed_settings_id'), table_name='feed_settings')
    op.drop_table('feed_settings')
    op.drop_index(op.f('ix_camera_feeds_id'), table_name='camera_feeds')
    op.drop_table('camera_feeds')
    # ### end Alembic commands ###
