"""updated feed schema

Revision ID: 79e463f1092b
Revises: 274ff5a47469
Create Date: 2025-12-18 10:55:59.151416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e463f1092b'
down_revision: Union[str, Sequence[str], None] = '274ff5a47469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera_feeds', sa.Column('rolling_confidence_sum', sa.Float(), nullable=True))
    op.add_column('camera_feeds', sa.Column('total_detection_count', sa.Integer(), nullable=True))
    op.drop_column('camera_feeds', 'current_detections')
    op.add_column('detections', sa.Column('feedback_status', sa.String(length=50), nullable=True))
    op.add_column('detections', sa.Column('feedback_comment', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detections', 'feedback_comment')
    op.drop_column('detections', 'feedback_status')
    op.add_column('camera_feeds', sa.Column('current_detections', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('camera_feeds', 'total_detection_count')
    op.drop_column('camera_feeds', 'rolling_confidence_sum')
    # ### end Alembic commands ###
