"""updated detection table

Revision ID: b36b48ed7cd8
Revises: 617ede3e77f6
Create Date: 2025-12-15 10:24:45.848365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b36b48ed7cd8'
down_revision: Union[str, Sequence[str], None] = '617ede3e77f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('context_tags', sa.JSON(), nullable=True))
    op.drop_column('detections', 'metadata_')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('metadata_', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('detections', 'context_tags')
    # ### end Alembic commands ###
