"""Add description column to detections table

Revision ID: 9541d0ab07d0
Revises: d98c80aad7ae
Create Date: 2025-12-13 23:57:21.438997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9541d0ab07d0'
down_revision: Union[str, Sequence[str], None] = 'd98c80aad7ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detections', 'description')
    # ### end Alembic commands ###
